### ISSUE TITLE
Error in running the plugin

### ISSUE THREAD

**Issue by pcav** [ArMoraer/QGISStrahler#2]
I selected a river, then just starting the plugin returned this error:

IndexError: list index out of range 
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/QGISStrahler-master/strahler.py", line 426, in run
    res, self.rootEndPoint = self.checkSelectedFeature( featureList )
  File "/home/paolo/.qgis2/python/plugins/QGISStrahler-master/strahler.py", line 362, in checkSelectedFeature
    endPt0 = points[0]
IndexError: list index out of range

**Comment by ArMoraer** [comment]
That's strange. Could you send me your shapefile?

**Comment by pcav** [comment]
[fiumi.zip](https://github.com/ArMoraer/QGISStrahler/files/146782/fiumi.zip)

**Comment by pcav** [comment]
I selected the longest river (arno)

**Comment by ArMoraer** [comment]
Ok, I understand. This is because the layer has multipart (multipolyline) features, which are currently not handled by the plugin. I will fix that in a few minutes (by checking the geometry during the plugin startup).

**Comment by pcav** [comment]
Thanks. I think this is a common case, so good to fix it.
Please let me know when you have a new version, so I can promptly approve it.

**Comment by ArMoraer** [comment]
I just committed the fix. Should I upload again the plugin to https://plugins.qgis.org/plugins, or is it fine like that?

**Comment by pcav** [comment]
pleas eupload a new version, with higher number
